[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "4ezuim4CP3uyumVRbQnDcy1UVKs4iAHcnrk7LvM2haXk"

[provider]
cluster = "localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
