[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
amm = "BHXF68PTvS1KXaix4HywUqP9DJWMjaNkSLZt1KSuTswZ"

[programs.localnet]
amm = "4ezuim4CP3uyumVRbQnDcy1UVKs4iAHcnrk7LvM2haXk"

[provider]
cluster = "devnet"
wallet = "C:/Users/ardhe/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
